---
- name: Update APT
  hosts: all
  become: yes

  tasks:
    - name: Update repositories
      apt:
          cache_valid_time: 86400
          update_cache: yes

- name: Install & configure openvpn
  hosts: all
  become: yes
  roles:
    - openvpn

- name: Configure fail2ban for openvpn
  hosts: all
  become: yes
  roles:
    - fail2ban
