---
- name: Create openvpn filter
  ansible.builtin.copy:
    src: openvpn.filter
    dest: /etc/fail2ban/filter.d/openvpn.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Create openvpn jail
  ansible.builtin.copy:
    src: openvpn.jail
    dest: /etc/fail2ban/jail.d/openvpn.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
