---
- name: install openvpn
  ansible.builtin.apt:
      name: openvpn
      state: present

- name: enable openvpn service
  ansible.builtin.systemd:
    name: openvpn-server@server
    state: stopped
    enabled: true

- name: copy ca.crt
  ansible.builtin.copy:
    src: ca/ca.crt
    dest: /etc/openvpn/server/ca.crt
    owner: root
    group: root
    mode: '0644'

- name: copy dh.pem
  ansible.builtin.copy:
    src: ca/dh.pem
    dest: /etc/openvpn/server/dh2048.pem
    owner: root
    group: root
    mode: '0644'

- name: copy relay.crt
  ansible.builtin.copy:
    src: ca/Relay.crt
    dest: /etc/openvpn/server/Relay.crt
    owner: root
    group: root
    mode: '0644'

- name: copy relay.key
  ansible.builtin.copy:
    src: ca/Relay.key
    dest: /etc/openvpn/server/Relay.key
    owner: root
    group: root
    mode: '0600'

- name: copy relay.pass
  ansible.builtin.copy:
    src: ca/Relay.pass
    dest: /etc/openvpn/server/Relay.pass
    owner: root
    group: root
    mode: '0600'

- name: copy ta.key
  ansible.builtin.copy:
    src: ca/ta.key
    dest: /etc/openvpn/server/ta.key
    owner: root
    group: root
    mode: '0600'

- name: copy client configuration
  ansible.builtin.copy:
    src: resources/ccd
    dest: /etc/openvpn/server/
    owner: root
    group: root
    mode: '0644'

- name: copy server configuration
  ansible.builtin.copy:
    src: server.conf
    dest: /etc/openvpn/server/server.conf
    owner: root
    group: root
    mode: '0644'

- name: open udp 1194
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: udp
    destination_port: 1194
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new OpenVPN connections

- name: save iptables
  ansible.builtin.shell:
    cmd: iptables-save > /etc/iptables/rules.v4

- name: create log directory
  ansible.builtin.file:
    path: /var/log/openvpn
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create log file
  ansible.builtin.file:
    path: /var/log/openvpn/openvpn.log
    state: touch
    owner: root
    group: root
    mode: 0644

- name: start openvpn service
  ansible.builtin.systemd:
    name: openvpn-server@server
    state: started
