---
- name: Install openvpn
  ansible.builtin.apt:
      name: openvpn
      state: present

- name: Enable openvpn service
  ansible.builtin.systemd:
    name: openvpn-server@server
    state: stopped
    enabled: true

- name: Copy ca.crt
  ansible.builtin.copy:
    src: ca/ca.crt
    dest: /etc/openvpn/server/ca.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy dh.pem
  ansible.builtin.copy:
    src: ca/dh.pem
    dest: /etc/openvpn/server/dh2048.pem
    owner: root
    group: root
    mode: '0644'

- name: Copy relay.crt
  ansible.builtin.copy:
    src: ca/Relay.crt
    dest: /etc/openvpn/server/Relay.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy relay.key
  ansible.builtin.copy:
    src: ca/Relay.key
    dest: /etc/openvpn/server/Relay.key
    owner: root
    group: root
    mode: '0600'

- name: Copy relay.pass
  ansible.builtin.copy:
    src: ca/Relay.pass
    dest: /etc/openvpn/server/Relay.pass
    owner: root
    group: root
    mode: '0600'

- name: Copy ta.key
  ansible.builtin.copy:
    src: ca/ta.key
    dest: /etc/openvpn/server/ta.key
    owner: root
    group: root
    mode: '0600'

- name: Copy client configuration
  ansible.builtin.copy:
    src: resources/ccd
    dest: /etc/openvpn/server/
    owner: root
    group: root
    mode: '0644'

- name: Copy server configuration
  ansible.builtin.copy:
    src: server.conf
    dest: /etc/openvpn/server/server.conf
    owner: root
    group: root
    mode: '0644'

- name: Open udp 1194
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: udp
    destination_port: 1194
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new OpenVPN connections

- name: Save iptables
  ansible.builtin.shell:
    cmd: iptables-save | grep -v f2b- > /etc/iptables/rules.v4

- name: Create log directory
  ansible.builtin.file:
    path: /var/log/openvpn
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create log file
  ansible.builtin.file:
    path: /var/log/openvpn/openvpn.log
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Start openvpn service
  ansible.builtin.systemd:
    name: openvpn-server@server
    state: started
